In [36]:
a=1.1
print(a)

1.1

In [37]:
list1=range(1, 10)
print(list(list1))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
lst=[5,1,5,12,4,423,423,423,423,4,23]
print("Array elements:", lst)
lst[0:6:1]


list(range(1,5,2))

Array elements: [5, 1, 5, 12, 4, 423, 423, 423, 423, 4, 23]

[1, 3]

In [39]:
# 2*1 = 2

for i in range(0, 11):
    print(f"2 * {i} = {2*i}")
    if i==11:
        print("End of table")

print("Continuing...")

2 * 0 = 0
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20
Continuing...

In [40]:
# *
# **
# ***

for i in range(1, 4):
    print('*' * i)
# ***
# **
# *
for i in range(10, 0,-2):
    print('*' * i)

*
**
***
**********
********
******
****
**

In [41]:
# *****
#  ***
#   *
for i in range(5, 0, -2):
    print(' ' * ((5 - i)//2) + '*' * i)

*****
 ***
  *

*Star Pattern printing cross odd length numbers*

In [42]:
nums = "1234567"

for i in range(len(nums)):
    for j in range(len(nums)):
        if i == j or i + j == len(nums)-1:
            print(nums[i], end = " ")
        else:
            print(" ", end = " ")
    print()

1           1
  2       2
    3   3
      4
    5   5
  6       6
7           7

*Star Pattern printing cross odd length numbers*

In [43]:
nums = "7654321"

for i in range(len(nums)):
    for j in range(len(nums)):
        if i == j or i + j == len(nums)-1:
            print(nums[j], end = " ")
        else:
            print(" ", end = " ")
    print()

7           1
  6       2
    5   3
      4
    5   3
  6       2
7           1

*Pattern printing numbers*

In [44]:
nums = 4

for i in range(nums):
    k = 111
    for j in range(i+1):
        print(k, end =" ")
        k += 111
    print()

111
111 222
111 222 333
111 222 333 444

*Pattern printing numbers*

In [45]:
nums = 5

for i in range(nums):
    k = 111
    for j in range(nums-i-1):
        print("   ", end = " ")
    for j in range(i+1):
        print(k, end =" ")
        k += 111
    print()

                111
            111 222
        111 222 333
    111 222 333 444
111 222 333 444 555

*Pattern printing numbers*

In [46]:
nums = 5

for i in range(nums):
    k = 111
    for j in range(nums-i-1):
        print("   ", end = " ")
    k *= (i+1)
    for j in range(i+1):
        print(k, end =" ")
        k -= 111
    print()

                111
            222 111
        333 222 111
    444 333 222 111
555 444 333 222 111

Diamond Star Pattern

In [47]:
row = 5
for i in range(row):
    for j in range(row-i):
        print(format("*", "<2"), end = "")
    for j in range(row - (row-i)):
        print(format("","<1"), end = "")
    # print()
    for j in range(row - (row-i)):
        print(format(" ", ">3"), end = "")
    for j in range(row-i):
        print(format("*", ">2"), end = "")
    print()

for i in range(row):
    for j in range(i+1):
        print(format("*", "<2"), end = "")
    for j in range(row-1-i):
        print(format("", "<1"), end = "")
    for j in range(row-1-i):
        print(format(" ", ">3"), end = "")
    for j in range(i+1):
        print(format("*", ">2"), end = "")

    print()

* * * * *  * * * * *
* * * *      * * * *
* * *          * * *
* *              * *
*                  *
*                  *
* *              * *
* * *          * * *
* * * *      * * * *
* * * * *  * * * * *

LCM

In [48]:
class Solution:
    # @staticmethod
    def Compute_LCM(self,n1, n2):
        if n1 > n2:
            higher = n1
        else:
            higher = n2

        value = higher

        while True:
            if higher % n1 == 0 and higher % n2 == 0:
                return(f"LCM of {n1} and {n2} is {higher}")
                break
            else:
                higher += value
sol = Solution()
print(sol.Compute_LCM(108,901))

LCM of 108 and 901 is 97308

Diamond Numbers Pattern

In [49]:
# Q: Number Diamond Pattern

num = 9
# For space we can do this as well but this will not work for any number of row so have to neglect this approach
# space = (num*2)+1-(row*3) when num = 4

for row in range(num):
    for col in range(num-1-row):
        print(" ", end = "  ")
    for col in range(row+1,0,-1):
        print(col, end = " ")
    if row > 0:
        for col in range(row-1):
            print(" ", end = " ")
        for col in range(row+1):
            print(col+1, end = " ")               
    print()

for row in range(num-1):
    for col in range(row+1):
        print(" ", end = "  ")
    for col in range(num-1-row,0,-1):
        print(col, end = " ")
    if row < (num-2):
        for col in range(num-row-3):
            print(" ", end = " ")
        for col in range(num-row-1):
            print(col+1, end = " ")               
    print()

                        1
                     2 1 1 2
                  3 2 1   1 2 3
               4 3 2 1     1 2 3 4
            5 4 3 2 1       1 2 3 4 5
         6 5 4 3 2 1         1 2 3 4 5 6
      7 6 5 4 3 2 1           1 2 3 4 5 6 7
   8 7 6 5 4 3 2 1             1 2 3 4 5 6 7 8
9 8 7 6 5 4 3 2 1               1 2 3 4 5 6 7 8 9
   8 7 6 5 4 3 2 1             1 2 3 4 5 6 7 8
      7 6 5 4 3 2 1           1 2 3 4 5 6 7
         6 5 4 3 2 1         1 2 3 4 5 6
            5 4 3 2 1       1 2 3 4 5
               4 3 2 1     1 2 3 4
                  3 2 1   1 2 3
                     2 1 1 2
                        1

In [50]:
2**7 *4

512

In [ ]:
# !pip install openpyxl --quiet
# !pip install skimpy
# pip install skimpy

In [52]:
import pandas as pd
import seaborn as sns
# import ydata_profiling as yd # this is under only ydata conda env
from skimpy import skim 
tit = sns.load_dataset("titanic")
tit.to_excel("./DataSets/tit.xlsx")
tit.to_csv("./DataSets/tit.csv")

In [53]:
# df = pd.read_csv("./DataSets/tit.csv")
# df_2 = pd.read_excel("./DataSets/tit.xlsx")
df = tit
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [54]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [55]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [56]:
df.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [57]:
# profile = yd.ProfileReport(df)
# profile.to_file(output_file='./Outputs/ydata_titanic.html')

In [58]:
# df_1 = pd.read_csv('./DataSets/sdp.csv')
# profile = yd.ProfileReport(df_1)
# profile.to_file(output_file='./Outputs/ydata_pakpop.html')

In [59]:
skim(df)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types               Categories                                        │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓ ┏━━━━━━━━━━━━━━━━━━━━━━━┓                                │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃ ┃ Categorical Variables ┃                                │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩ ┡━━━━━━━━━━━━━━━━━━━━━━━┩                                │
│ │ Number of rows    │ 891    │ │ string      │ 5     │ │ class                 │                                │
│ │ Number of columns │ 15     │ │ int64       │ 4     │ │ deck                  │                                │
│ └───────────────────┴────────┘ │ float64     │ 2     │ └───────────────────────┘                                │
│                                │ category    │ 2     │                                                          │
│                                │ bool        │ 2     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━┳━━━━━━━┳━━━━━━━━┓  │
│ ┃ column    ┃ NA   ┃ NA %                 ┃ mean    ┃ sd      ┃ p0    ┃ p25   ┃ p50   ┃ p75 ┃ p100  ┃ hist   ┃  │
│ ┡━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━╇━━━━━━━╇━━━━━━━━┩  │
│ │ survived  │    0 │                    0 │  0.3838 │  0.4866 │     0 │     0 │     0 │   1 │     1 │ █    ▅ │  │
│ │  pclass   │    0 │                    0 │   2.309 │  0.8361 │     1 │     2 │     3 │   3 │     3 │ ▄  ▃ █ │  │
│ │    age    │  177 │   19.865319865319865 │    29.7 │   14.53 │  0.42 │ 20.12 │    28 │  38 │    80 │ ▂██▃▁  │  │
│ │   sibsp   │    0 │                    0 │   0.523 │   1.103 │     0 │     0 │     0 │   1 │     8 │   █    │  │
│ │   parch   │    0 │                    0 │  0.3816 │  0.8061 │     0 │     0 │     0 │   0 │     6 │  █▁▁   │  │
│ │   fare    │    0 │                    0 │    32.2 │   49.69 │     0 │  7.91 │ 14.45 │  31 │ 512.3 │   █    │  │
│ └───────────┴──────┴──────────────────────┴─────────┴─────────┴───────┴───────┴───────┴─────┴───────┴────────┘  │
│                                                    category                                                     │
│ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┓  │
│ ┃ column          ┃ NA        ┃ NA %                                    ┃ ordered           ┃ unique         ┃  │
│ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━┩  │
│ │      class      │         0 │                                       0 │ False             │              3 │  │
│ │      deck       │       688 │                       77.21661054994388 │ False             │              8 │  │
│ └─────────────────┴───────────┴─────────────────────────────────────────┴───────────────────┴────────────────┘  │
│                                                      bool                                                       │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column                            ┃ true            ┃ true rate                     ┃ hist                 ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │            adult_male             │             537 │                           0.6 │        ▅    █        │  │
│ │               alone               │             537 │                           0.6 │        ▅    █        │  │
│ └───────────────────────────────────┴─────────────────┴───────────────────────────────┴──────────────────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃           ┃    ┃           ┃          ┃           ┃          ┃           ┃ chars    ┃ words per ┃ total    ┃  │
│ ┃ column    ┃ NA ┃ NA %      ┃ shortest ┃ longest   ┃ min      ┃ max       ┃ per row  ┃ row       ┃ words    ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━┩  │
│ │    sex    │  0 │         0 │   male   │  female   │  female  │   male    │      4.7 │         1 │      891 │  │
│ │ embarked  │  2 │ 0.2244668 │    S     │     S     │    C     │     S     │        1 │         1 │      889 │  │
│ │           │    │ 911335578 │          │           │          │           │          │           │          │  │
│ │    who    │  0 │         0 │   man    │   woman   │  child   │   woman   │     3.79 │         1 │      891 │  │
│ │ embark_to │  2 │ 0.2244668 │ Cherbour │ Southampt │ Cherbour │ Southampt │     10.5 │         1 │      889 │  │
│ │    wn     │    │ 911335578 │    g     │    on     │    g     │    on     │          │           │          │  │
│ │   alive   │  0 │         0 │    no    │    yes    │    no    │    yes    │     2.38 │         1 │      891 │  │
│ └───────────┴────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

In [60]:
# Reading the dataset
#  ...existing code...
df_02 = pd.read_csv('./DataSets/Playstore_final.csv', engine='python', on_bad_lines='skip', sep=',')
# ...existing code...

In [61]:
# 
df_02.head()

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Free,Price,Currency,...,Ad Supported,In app purchases,Editor Choice,Summary,Reviews,Android version Text,Developer,Developer Address,Developer Internal ID,Version
0,Logistics Management,com.eniseistudio.logistics_management,Education,4.090909,66.0,"10,000+",10000.0,True,0.0,USD,...,True,False,False,Leading Online Learning and Training System in...,28.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656447e+18,1.1.5
1,Estados Unidos Noticias,com.eniseistudio.news.estados_unidos,News & Magazines,4.000000,8.0,"1,000+",1000.0,True,0.0,USD,...,True,False,False,Top Stories\r\nWorld\r\nEntertainment\r\nSport...,3.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656447e+18,1.2.3
2,Dental Assistant,com.eniseistudio.dental_assistant,Education,3.866667,15.0,"10,000+",10000.0,True,0.0,USD,...,True,False,False,"Dental Assistant: Study Dental Assistant, Dent...",3.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656447e+18,1.1.5
3,Medical Assistant,com.eniseistudio.course.medical_assistant,Education,4.000000,18.0,"5,000+",5000.0,True,0.0,USD,...,True,False,False,Medical Assistant Degree Medical Assistant Job...,7.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656447e+18,1.1.4
4,Business Administration,com.eniseistudio.majors.course.business_admini...,Education,4.023256,86.0,"50,000+",50000.0,True,0.0,USD,...,True,False,False,"Business Administration Learning, Business Adm...",29.0,4.0 and up,eniseistudio,"7115 N Muscatel Ave San Gabriel, CA 91775 Unit...",4.656447e+18,1.1.6

In [62]:
df_02.tail()

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Free,Price,Currency,...,Ad Supported,In app purchases,Editor Choice,Summary,Reviews,Android version Text,Developer,Developer Address,Developer Internal ID,Version
450788,Punjabi Keyboard,com.fancy.fontforu.punjabikeyboard,Productivity,4.240000,875.0,"100,000+",100000.0,True,0.0,USD,...,True,False,False,Pubjabi keyboard app which allow you to type i...,257.0,4.1 and up,Fancy Font For U,NaN,5.362128e+18,13
450789,Live 4D Wallpaper 2020 : 4K Live Backgrounds,com.fancy.hdwallpaper.parallaxbackgroundhd,Personalization,2.961539,52.0,"10,000+",10000.0,True,0.0,USD,...,NaN,False,False,Unlimited Live 4D Wallpapers collection to dec...,26.0,4.2 and up,Fancy Font For U,NaN,5.362128e+18,1
450790,Rap Music Maker : Rap Beats Music Recording St...,com.fancy.rapmusicmakerstudio,Music & Audio,3.500000,64.0,"10,000+",10000.0,True,0.0,USD,...,True,False,False,Rap Music Maker will used to make your own rap...,41.0,5.0 and up,Fancy Font For U,NaN,5.362128e+18,2.3
450791,Meetz - Cloud Meetings and Classes,org.ssz.meet,Communication,NaN,NaN,"5,000+",5000.0,True,0.0,USD,...,NaN,False,False,Virtual meetings for everyone,NaN,Varies with device,INVENTRIX,NaN,7.185660e+18,Varies with device
450792,SWACU Mobile,com.southwest.mobile,Finance,2.860000,150.0,"10,000+",10000.0,True,0.0,USD,...,NaN,False,False,SWACU Mobile,80.0,4.4 and up,Southwest Airlines Federal Credit Union,"2430 Shorecrest Drive\r\nDallas, TX 75235",7.668341e+18,19.4

In [63]:
# Checking data info
df_02.info()

<class 'pandas.DataFrame'>
RangeIndex: 450793 entries, 0 to 450792
Data columns (total 29 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   App Name               450780 non-null  str
 1   App Id                 450793 non-null  str
 2   Category               450780 non-null  str
 3   Rating                 447981 non-null  float64
 4   Rating Count           332025 non-null  float64
 5   Installs               450702 non-null  str
 6   Minimum Installs       450780 non-null  float64
 7   Free                   450701 non-null  object
 8   Price                  450701 non-null  float64
 9   Currency               450701 non-null  str
 10  Size                   450765 non-null  str
 11  Minimum Android        449711 non-null  str
 12  Developer Id           450777 non-null  str
 13  Developer Website      341067 non-null  str
 14  Developer Email        450767 non-null  str
 15  Released               447346 non-null  str
 16  Last update            450793 non-null  str
 17  Privacy Policy         399945 non-null  str
 18  Content Rating         450780 non-null  str
 19  Ad Supported           281063 non-null  object
 20  In app purchases       450793 non-null  bool
 21  Editor Choice          450793 non-null  bool
 22  Summary                450592 non-null  str
 23  Reviews                447981 non-null  float64
 24  Android version Text   449711 non-null  str
 25  Developer              450777 non-null  str
 26  Developer Address      262001 non-null  str
 27  Developer Internal ID  450780 non-null  float64
 28  Version                450620 non-null  str
dtypes: bool(2), float64(6), object(2), str(19)
memory usage: 93.7+ MB

In [64]:
# profile1 = yd.ProfileReport(df_02)
# profile1.to_file(output_file='./Outputs/ydata_playstore.html')

In [74]:
df_02.sample(10)

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Free,Price,Currency,...,Ad Supported,In app purchases,Editor Choice,Summary,Reviews,Android version Text,Developer,Developer Address,Developer Internal ID,Version
47707,Hidden my phone by mom 2 - escape game,com.tyou.shouji2,Casual,3.920000,990.0,"100,000+",100000.0,True,0.00,USD,...,True,False,False,My mom hide my phone again.I have to find it.,434.0,4.1 and up,99key,Tokyo,9.014234e+18,1.1
99702,Orbic Purple Icons Pack,com.sam.orbic.purple,Personalization,0.000000,NaN,10+,10.0,False,1.99,USD,...,NaN,True,False,• A set of icons that is not constrained to th...,0.0,5.0 and up,Sam Icons,Trust Colony House 10,4.647830e+18,2
129303,Channelify - Channel to App,aculix.channelify.app,Libraries & Demo,3.400000,5.0,100+,100.0,True,0.00,USD,...,True,False,False,Simple & beautiful app to show videos from you...,2.0,5.0 and up,Aculix Technologies LLP,"Tivoli, Godrej Garden City, Ahmedabad, India",8.784124e+18,1.32
226675,HomeWhiz,com.homewhiz.global,Lifestyle,1.906404,2015.0,"100,000+",100000.0,True,0.00,USD,...,NaN,False,False,HomeWhiz smart home technology will put your h...,1632.0,5.0 and up,Arcelik A.Ş.,NaN,5.888902e+18,2.5.0
391726,Best Trace,net.ipip.traceroute,Tools,4.440000,144.0,"10,000+",10000.0,True,0.00,USD,...,NaN,False,False,The best visual Traceroute tool！,55.0,4.0.3 and up,北京天特信科技有限公司,NaN,4.771893e+18,1.16
435410,super indie karts,com.newandromo.dev535927.app768056,Racing,3.142857,7.0,"1,000+",1000.0,True,0.00,USD,...,True,False,False,Super indie car game application,3.0,4.1 and up,ahmed alrifay,NaN,7.185188e+18,1.3
290381,Croatia News (Hrvatska),com.adelinolobao.croatianews,News & Magazines,4.445545,534.0,"10,000+",10000.0,True,0.00,USD,...,True,False,False,Fast way to read Croatia (Hrvatska) News (Vije...,138.0,4.1 and up,All About News,NaN,5.480632e+18,7.2
150080,সাধারণ জ্ঞান ২০২০,com.shahidul.shadarongaayn,Lifestyle,0.000000,NaN,100+,100.0,True,0.00,USD,...,True,False,False,"বাংলা,ইংলিশ,গনিত,মহাবিশ্ব,সম্পর্কে সাধারন জ্ঞা...",0.0,4.0.3 and up,Afifa Akter,NaN,8.558745e+18,1
286433,Track Kit,com.lifewaresolutions.trackkit,Travel & Local,3.970297,163.0,"10,000+",10000.0,True,0.00,USD,...,NaN,False,False,Track Kit – Share Your Travel Experience: rout...,78.0,4.4 and up,LWS Research,"LWS Research, Inc.,\r\n8721 Santa Monica Blvd,...",6.189305e+18,1.5.0
299303,Rap Music Hits- 80s till date,com.andromo.dev405493.app926614,Entertainment,0.000000,NaN,"1,000+",1000.0,True,0.00,USD,...,True,False,False,Enjoy all the best rap hip hop hits of all tim...,0.0,4.1 and up,Ready Player Apps,NaN,9.166933e+18,1

In [75]:
df_02.describe()

,Rating,Rating Count,Minimum Installs,Price,Reviews,Developer Internal ID
count,447981.000000,3.320250e+05,4.507800e+05,450701.000000,4.479810e+05,4.507800e+05
mean,3.018797,1.942930e+04,8.836410e+05,0.315507,5.118347e+03,6.932302e+18
std,1.860019,6.642926e+05,3.607634e+07,4.110269,1.993118e+05,1.342447e+18
min,0.000000,3.000000e+00,0.000000e+00,0.000000,0.000000e+00,4.611695e+18
25%,0.000000,2.400000e+01,5.000000e+02,0.000000,0.000000e+00,5.771977e+18
50%,3.933333,1.230000e+02,5.000000e+03,0.000000,1.700000e+01,6.939067e+18
75%,4.390000,9.900000e+02,5.000000e+04,0.000000,1.780000e+02,8.109846e+18
max,5.000000,1.386210e+08,1.000000e+10,400.000000,5.237720e+07,9.223355e+18

In [84]:
df_02['Price'].value_counts()
df_02['Price'].isnull().sum()

np.int64(92)

In [85]:
df_02['Free'].value_counts()
df_02['Free'].isnull().sum()

np.int64(92)

In [91]:
df_02['App Id'].value_counts()

App Id
com.candy.cursh.match.game             2
com.onepeloton.callisto                2
com.walks99.walks99                    2
com.dietbet.app                        2
kerasinosapps.apps.diethelper          2
                                      ..
jp.gr.java_conf.appdev.app.explorer    1
com.dm.apps.smart.taskmanager.st       1
com.dar.prison.escape                  1
com.earnit.rb7                         1
com.wholesale7.yxm                     1
Name: count, Length: 422657, dtype: int64

In [93]:
# Filter rows where App Id is not null AND Price is null AND Free is null
result = df_02[(df_02['App Id'].notna()) & (df_02['Price'].isna()) & (df_02['Free'].isna())]

# Display the result
# print(result)

# Count how many rows match this condition
print(f"Number of rows: {len(result)}")

# Show specific columns
print(result[['App Id', 'Price', 'Free']])

Number of rows: 92
                                    App Id  Price Free
13103     id.akusantri.wallpapermuslimahhd    NaN  NaN
17210                    com.gamehouse.cc1    NaN  NaN
19030         com.volcanoforce.lost.global    NaN  NaN
19196              com.onemt.mafiacrimewar    NaN  NaN
19197                 and.onemt.moderndead    NaN  NaN
...                                    ...    ...  ...
272281   com.daviddickball.zombiewasteland    NaN  NaN
291626                 com.aramex.ecourier    NaN  NaN
291897              com.winrgames.letsleap    NaN  NaN
292192                      com.newspitara    NaN  NaN
293813  com.appfile.radiomelodiariojaneiro    NaN  NaN

[92 rows x 3 columns]

In [ ]:
# Show row indices
print(result.index.tolist()) #printing

[13103, 17210, 19030, 19196, 19197, 19342, 19514, 19559, 19805, 19806, 20506, 21479, 21864, 21902, 22461, 22480, 22498, 22784, 22997, 23027, 23037, 24463, 24464, 24465, 24496, 24497, 24517, 26015, 26046, 26174, 26757, 28737, 29534, 29813, 32524, 33298, 33299, 35049, 35688, 36865, 39832, 40732, 40790, 40817, 40824, 41488, 41531, 43390, 43651, 43703, 50260, 50885, 50897, 53450, 53455, 54815, 55067, 55389, 55415, 60230, 60291, 60654, 89548, 89897, 89908, 89928, 100476, 101796, 101892, 104772, 104783, 105234, 110672, 110733, 110846, 110862, 110898, 110910, 111035, 111378, 134391, 144829, 144883, 163930, 195173, 200169, 245437, 272281, 291626, 291897, 292192, 293813]